[project]
name = 'Quantum-Archaeology-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.quantum-nft]
path = 'contracts/quantum-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.research-management]
path = 'contracts/research-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
